# Generated by Django 5.1.7 on 2025-03-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_booking_length', models.IntegerField(default=3)),
                ('max_booking_length', models.IntegerField(default=30)),
                ('max_guests_per_booking', models.IntegerField(default=10)),
                ('breakfast_price', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
